---
title: "Preparation for SPISE"
subtitle: "Workshop 2: A multi-dimensional approach using MCA, MFA, and PLS with R"
author: "Phu Nguyen-Duc"
date: "2024-07-22"
categories: [r, learning, spise, multivariate, multi-dimensional, MCA, MFA, PLS]
---

Buổi workshop gồm 2 phần chính, cho 2 ngày:

1. Tìm mối tương quan giữa 2 bộ dữ liệu cho cùng một sản phẩm
2. Dự đoán một bảng dữ liệu (thuộc tính) từ một bảng khác

Document này tổng hợp một số kiến thức nền về mặt concept để chuẩn bị cho buổi workshop một cách hiệu quả.

# Background

Section này ôn lại một số khái niệm cơ bản trong phân tích dữ liệu như tương quan (correlation), thu giảm số chiều (dimensionality reduction) và hồi quy đa biến (multiple regression)

## Correlation

[Resource](https://en.wikipedia.org/wiki/Correlation_coefficient)

Hệ số tương quan là một phép đo cho tương quan tuyến tính giữa 2 biến (có thể là thuộc tính, quan sát, bộ dữ liệu, etc.). Lưu ý rằng hệ số tương quan có thể bị ảnh hưởng đáng kể bởi outlier và không thể hiện tính causal của 2 biến.

Một số phân loại cho hệ số tương quan, tuỳ thuộc vào kiểu dữ liệu của biến đang được xét đến (liên tục, rời rạc có thứ tự hay rời rạc không thức tự):

### Pearson 

Còn được gọi là inter-class correlation.

Hệ số tương quan Pearson là một phép đo thể hiện độ lớn và hướng của mối quan hệ tuyến tính giữa 2 biến, được tính bằng hiệp phương sai^[Giá trị kỳ vọng của tích 2 biến trừ cho tích 2 giá trị kì vọng của từng biến] (covariance) chia cho tích độ lệch chuẩn (standard deviation) của 2 biến đó.

### Intra-class

Hay Intra-class correlation coefficient (ICC).

Là một phép đo định lượng được thực hiện trên các mẫu trong cùng một nhóm, để thể hiện mức độ tương đồng giữa các mẫu đó. Khác với correlation thường được tính toán trên một cặp biến, ICC thường được thực hiện trên một nhóm các quan sát.

### Rank

Áp dụng cho dữ liệu rời rạc có thứ tự (ordinal scale). Thể hiện mức độ giống nhau giữa 2 "bảng xếp hạng" (rankings).

## Dimensionality reduction

Thu giảm số chiều của tập dữ liệu ban đầu mà vẫn giữ được phần lớn lượng thông tin. Một số kỹ thuật trong dimensionality reduction như SVD (singular value decomposition) và PCA (principle component analysis)

SVD trả lời câu hỏi: Ma trận ban đầu trải dài các vector theo hướng nào?^[In what direction the matrix strecth an unit vector the most?]

Phần tiếp theo liên quan đến key concept cho các phương pháp sẽ được thảo luận trong workshop

# Find information between two tables

Focus vào tương quan của 2 bảng dữ liệu

### Canonical Correlation Analysis (CCA)

- **Goal**: Xác định mối liên hệ tuyến tính mạnh nhất (rõ rệt nhất) giữa 2 bảng dữ liệu 
- **Focus**: Tập trung vào tương quan, tìm các cặp biến ngẫu nhiên có tương quan cao nhất

### Partial Least Squares - Canonical Correlation (PLS-C)

- **Goal**: Tìm biến ẩn (latent variables) giải thích mối tương quan lớn nhất giữa 2 tập hợp đặc trưng
- **Focus**: Tập trung vào mối quan hệ giữa các tập hợp biến và không yêu cầu giống nhau về số lượng biến

# Predict a table from the other one

Focus vào predictive model

### Redundancy Analysis (RDA/RA)

- **Goal**: với concept chính là giải thích các biến phản hồi (response variables) bằng các biến giải thích (explanatory variables)
- **Focus**: tậpn trung chủ yếu vào quan hệ tuyến tính giữa 2 nhóm biến

### Partial Least Squares - Regression (PLS-R)

- **Goal**: tương tự như RDA
- **Focus**: mô hình phức tạp hơn, tập trung không chỉ vào mối quan hệ của các biến ẩn mà cả ảnh hưởng của các biến đo lường đến các biến ẩn tương ứng.

### Điểm khác biệt giữa RDA / CCA và PLS-R / PLS-C

RDA fit một mô hình CCA vào dữ liệu trong khi PLS-R sử dụng PLS path model. Điểm khác biệt về mặt kỹ thuật này cho phép RDA có lợi thế về mặt tính toán và diễn giải trong khi PLS-R có khả năng giải thích các mô hình phức tạp mà RDA sẽ gặp khó khăn.

# Một số lưu ý

- PLS đòi hỏi model mối liên hệ giữa các biến ẩn (latent variable) và các biến đo lường (measurement variable) trước khi nghĩ đến dữ liệu và cách thức thu thập dữ liệu. Do đó, model chủ yếu dựa vào kiến thức chuyên môn của lĩnh vực đang được xét đến.